<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="signup.spec"
    errors="0" failures="1" hostname="" id="" package="signup.spec" skipped="0"
    tests="1" time="51.29" timestamp="Tue, 30 May 2017 16:29:15 GMT">
  
    <testcase name="Sign up" classname="signup.spec" time="51.29" assertions="10">

    

    

    

    

    

    

    

    

      <failure message="Testing if the URL equals &quot;http://localhost:8080/chat&quot;.">    at Object.SignUp [as Sign up] (/Users/chineduofor/Desktop/PostIt/postit/postit/src/test/e2e/signup.spec.js:25:15)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
